### ISSUE TITLE
[ContactView] Improve post-onboarding experience 

### ISSUE THREAD

**Issue by alltheseas** [erdaltoprak/tamga#10]
_What happened_

Booted up Tamga with a test account (not sure if relevant: test account created with iOS Iris).

Successfully logged in with my nsec. Public key was successfully imported.

Handle, NIP-05, and contacts were not imported. 

Npub: 99eb5cf72b13f104d9896ac1806cee1ffa8ec662b4a65fd5402d230ddaa6d9a2

npub1n844eaetz0csfkvfdtqcqm8wrlaga3nzkjn9l42q953smk4xmx3qm75yml

_What I think should happen_
Automagically imported after nsec input:
-username
-NIP-05 ID
-contacts list

**Comment by erdaltoprak** [comment]
I've seen your reply on nostr, yes you have to tap pull contacts on the submenu in the main screen.
I could pull automatically but I hesitate to do it for two reasons:

- I want to do it gracefully by first accounting for network strength and bandwidth limitation of the user (cellular plan) or at the very least inform the user in some way 
- It kinda forces the user to acknowledge the fact that this is an offline first experience with relay pulling being needed from time to time

But i agree that some better UI/UX work could be done on it!

**Comment by alltheseas** [comment]
> I've seen your reply on nostr, yes you have to tap pull contacts on the submenu in the main screen. I could pull automatically but I hesitate to do it for two reasons:
> 
> * I want to do it gracefully by first accounting for network strength and bandwidth limitation of the user (cellular plan) or at the very least inform the user in some way
> * It kinda forces the user to acknowledge the fact that this is an offline first experience with relay pulling being needed from time to time
> 
> But i agree that some better UI/UX work could be done on it!

Got you. 

A couple questions:
1. Do you know how much data is taken up when 10, 100, 1000 profiles are pulled?
2. Can Tamga pull the contact data (which I think is public info) with a npub, in lieu of a nsec?

**Comment by alltheseas** [comment]
The UI is a bit hidden. Here is a mockup / suggestion that I think will:
1) remove onboarding friction
2) explicitly communicate your offline design

I am suggesting to remove the search bar, three dots in top right, and the "refresh to fetch your contacts..." message for new users.

![Onboarding home screen](https://user-images.githubusercontent.com/64376233/222875173-415f3431-7a08-42ed-a6b2-9a0500b1e3b5.png)

![Onboarding home screen tooltip expand](https://user-images.githubusercontent.com/64376233/222875169-8b85b166-2a58-42aa-a8f1-1a65c6ece1d5.png)

I used a gradient of orange from the Tamga icon.

**Comment by erdaltoprak** [comment]
> 1. Do you know how much data is taken up when 10, 100, 1000 profiles are pulled?

Not right now, I will have to experiment and gather more data on this, the biggest factor isn't really the number of profiles itself but more the assets (profile image / profile banner) that those profiles may have.

> 2. Can Tamga pull the contact data (which I think is public info) with a npub, in lieu of a nsec?

Yes and that was the case on the earlier versions before the rename / relaunch of the app. Since the goal is to have one place to check on your friends and connect to other apps, I included the nsec login only to emphasize on the role of key storage that the app should take. I could probably do more work on explaining the role of this nostr micro app better :-)

> The UI is a bit hidden. Here is a mockup / suggestion that I think will:
> 
> 1. remove onboarding friction
> 2. explicitly communicate your offline design
> 
> I am suggesting to remove the search bar, three dots in top right, and the "refresh to fetch your contacts..." message for new users.


Thanks a lot for the suggestions, I will definitely implement this!

**Comment by alltheseas** [comment]
> Since the goal is to have one place to check on your friends and connect to other apps

These are two different jobs-to-be-done, and perhaps may be valued differently by different users. 

I wonder if you are scaring away users who only want to collect their friends contact info, and _not_ use Tamga as a nsec manager. My gut reaction was to input my test profile nsec, which is not painful to use, compared to my main profile.

**Comment by erdaltoprak** [comment]
I'll accept PRs for a "reader view", alternatively i'll reimplement this after the few features/fixes already in the work. Meanwhile i've update the onboarding with better explanations and links to "Tamga help" about key safety.
