### ISSUE TITLE
Inconsistency: Public key displayed in npub, and copied in hex format [UX]

### ISSUE THREAD

**Issue by alltheseas** [erdaltoprak/tamga#11]
_What happens:_
In the profile view, my public key is displayed in npub format. When I tap to copy, the public key is copied in hex format.

_What I think should happen:_
What I see is what I get. When I tap copy on a npub, Tamga should store to memory the public key in the same format seen visually (i.e. npub, not hex).

**Comment by erdaltoprak** [comment]
Fixed!

Changed 

`UIPasteboard.general.string = self.profiles[0].id`

to 

`NostrKey.shared.bech32_pubkey(self.profiles[0].id ?? "")`

**Comment by alltheseas** [comment]
> Fixed!
> 
> Changed
> 
> `UIPasteboard.general.string = self.profiles[0].id`
> 
> to
> 
> `NostrKey.shared.bech32_pubkey(self.profiles[0].id ?? "")`

⚡ speed, nice!

Suggestion when you push new builds: add a "What's New" in the click-throughs after install, before app opens. Damus does this.

**Comment by erdaltoprak** [comment]
> Suggestion when you push new builds: add a "What's New" in the click-throughs after install, before app opens. Damus does this.

There should be a TestFlight generated/automated popup after a new version right ? (image below)
![testflight-first-view](https://user-images.githubusercontent.com/10966155/222901508-b6698fa2-1db6-4302-957f-ccc3d36f7095.jpeg)

If this is what you were referring to, I'll update that text for new features going forward and also update the changelog inside the app (settings > about > changelog) and on the website iid I don't forget :-)

**Comment by alltheseas** [comment]
Yes, this is the prompt I was referring to. Check out Damus upon testfight update as an example.

Example:

Added bookmarks
Fixed zaps
Fixed DM UI etc
